version = 1

exclude_patterns = [
  "src/scrilla/data/cache/**",
  "src/scrilla/data/common/**",
  "src/scrilla/data/sql/**",
  "src/scrilla/data/static/**",
  "env/**",
  "*.env",
  "*.pyc",
  ".gitignore",
  ".dockerignore"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "shell"
enabled = true

[[transformers]]
name = "autopep8"
enabled = true