version = 1

exclude_patterns = [
    "migrations/**",
    "data/cache/**",
    "data/common/**",
    "data/sql/**,
    "data/static/**",
    "env/**",
    "*.env",
    *.pyc,
    ".gitignore",
    ".dockerignore"
]

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = [
  "requirements.txt",
  "requirements-docker.txt"
]
    [analyzers.meta]
    runtime_version = "3.x.x"

[[analyzers]]
name = "docker"
enabled = true
    [analyzers.meta]
    dockerfile_paths = [
        "Dockerfile"
    ]

[[analyzers]]
name = "shell"
enabled = true
    [analyzers.meta]
    dialect = "bash"