version = 1

exclude_patterns = [
    "src/scrilla/data/cache/**",
    "src/scrilla/data/common/**",
    "src/scrilla/data/sql/**",
    "src/scrilla/data/static/**",
    "env/**",
    "*.env",
    "*.pyc",
    ".gitignore",
    ".dockerignore"
]

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = [
  "requirements.txt",
]
    [analyzers.meta]
    runtime_version = "3.x.x"

[[analyzers]]
name = "shell"
enabled = true
    [analyzers.meta]
    dialect = "bash"