version: "3.8"
services:
    app: 
      image: pynance:latest
      depends_on:
        - datasource
      ports:
        - "8000:8000"
      volumes:
        - static:/home/data/static/
        - cache:/home/data/cache
      networks:
        - data_net
        - app_net
      env_file: 
        - ./env/container.env
      command: ["wait-for-it"]

    web:
      image: pynance-web:latest
      ports: 
        - "8080:8080"
      networks:
        - app_net
      env_file:
        - ./env/container.env
        
    datasource:
      image: postgres:11
      restart: always
      ports: 
        - "5431:5432"
      volumes:
        - postgres:/var/lib/postgresql/data
      networks:
        - data_net
      env_file:
        - ./env/container.env 
    
    # queue:
      # image: redis:alpine
      # networks:
        # - the_pit

networks:
    data_net: 
    app_net:

volumes: 
    postgres:
    static:
    cache:
    redis: