version: "3.8"
services:
    app: 
      image: pynance:latest
      depends_on:
        - datasource
      ports:
        - "8000:8000"
      volumes:
        - static:/home/data/static/
        - cache:/home/data/cache
      networks:
        - the_pit
      env_file: 
        - ./env/container.env
      command: ["wait-for-it"]

    # web:
      # image: pynance-web:latest
      # ports: 
        # - "8080:8080"
      # networks:
        # - the_pit
      # env_file:
        # - ./env/container.env
        
    datasource:
      image: postgres:11
      restart: always
      ports: 
        - "5432:5432"
      volumes:
        - postgres:/var/lib/postgresql/data
      networks:
        - the_pit
      env_file:
        - ./env/container.env 
    
    queue:
      image: redis:alpine
      networks:
        - the_pit

networks:
    the_pit: 

volumes: 
    postgres:
    static:
    cache:
    redis: