version: "3.8"
services:
    app: 
      image: pynance:latest
      depends_on:
        - datasource
      ports:
        - "8000:8000"
      volumes:
        - static:/home/static/
      networks:
        - pynance
      env_file: 
        - ./env/container.env
      command: ["wait-for-it", "datasource:5432"]

    datasource:
      image: postgres:latest
      restart: always
      ports: 
          - "5432:5432"
      volumes:
          - postgres:/data/postgres
      networks:
          - pynance
      env_file:
          - ./env/container.env 

networks:
    pynance: 

volumes: 
    postgres:
    static: