version: "3.8"
services:
    app: 
      image: pynance:latest
      depends_on:
        - datasource
      ports:
        - "8000:8000"
      volumes:
        - static:/home/static/
        - cache:/home/cache
      networks:
        - the_pit
      env_file: 
        - ./env/container.env
      command: ["wait-for-it"]

    datasource:
      image: postgres:11
      restart: always
      ports: 
        - "5432:5432"
      volumes:
        - postgres:/data/postgres
      networks:
        - the_pit
      env_file:
        - ./env/container.env 

networks:
    the_pit: 

volumes: 
    postgres:
    static:
    cache: