version: 2.1

commands:
  install_python_deps:
    description: install python dependencies
    steps:
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: python-deps-v4-{{ checksum "requirements.txt"}}
      - run:
          name: python dependencies
          command: |
            python3 -m venv ./venv/
            source ./venv/bin/activate
            pip3 install -r requirements.txt
      - save_cache:
          key: python-deps-v4-{{ checksum "requirements.txt"}}
          paths:
            - "./venv/"

  build_wheel:
    description: compress and build python package
    steps:
      - restore_cache: 
          key: python-deps-v4-{{ checksum "requirements.txt"}}
      - run:
          name: artifact build
          environment:
            APP_ENV: container
          command: |
            source ./venv/bin/activate
            touch ./src/scrilla/data/cache/scrilla.db
            ./scripts/install
            scrilla version

  upload_artifacts:
    description: upload package artifacts to PyPi
    steps:
      - restore_cache: 
          key: python-deps-v4-{{ checksum "requirements.txt"}}
      - run:
          name: artifact upload
          command: |
            source ./venv/bin/activate
            twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*

  commit_version:
    description: commit new version to git
    steps:
      - run:
          name: commit version
          command: |
            git config user.email "chinchalinchin@gmail.com"
            git config user.name "CircleCi Bot"
            git stash
            git checkout develop/main
            git stash pop
            git add . 
            git commit -m "Pipeline Build Version $(cat ./src/scrilla/version.txt)" || true
            git push --set-upstream origin develop/main || true

  install_doc_deps:
    description: install documentation dependencies
    steps:
      - run:
          name: install virtual server & gui libraries
          command: sudo apt-get update -y && sudo apt-get install -y xvfb libopengl0 libegl1-mesa libxkbcommon-x11-0 ffmpeg libsm6 libxext6

  generate_package_docs:
    description: generate documentation html from docstrings
    steps:
      - restore_cache:
          key: python-deps-v4-{{ checksum "requirements.txt"}}
      - attach_workspace:
          at: docs
      - run:
          name: generate docs
          command: |
            source ./venv/bin/activate
            ./scripts/package-docs circle-ci
      - persist_to_workspace:
          root: docs
          paths: 
            - package
  
  generate_source_docs:
    description: generate documentation html from markdown
    steps:
      - restore_cache:
          key: python-deps-v4-{{ checksum "requirements.txt"}}
      - attach_workspace:
          at: docs
      - run:
          name: generate docs
          command: |
            source ./venv/bin/activate
            cd docs
            make html
      - persist_to_workspace:
          root: docs
          paths:
            - build/html

  install_test_deps:
    description: install testing libraries
    steps:
      - restore_cache:
          key: deepsource-v1
      - run:
          name: install deepsource cli
          command: |
            curl https://deepsource.io/cli | sh
            sudo apt-get update -y && sudo apt-get install -y libxkbcommon-x11-0 libopengl0 libegl1-mesa
      - save_cache:
          key: deepsource-v1
          paths:
            - "./bin/"
  
  run_unit_tests: 
    description: run unit tests
    steps:
      - restore_cache:
          key: deepsource-v1
      - restore_cache: 
          key: python-deps-v4-{{ checksum "requirements.txt"}}
      - attach_workspace:
          at: docs
      - run: 
          name: unit tests
          environment:
            APP_ENV: container
            AWS_DEFAULT_REGION: us-east-1
            LOG_LEVEL: none
          command: |
            source ./venv/bin/activate
            ./scripts/tests
            coverage xml
            ./bin/deepsource report --analyzer test-coverage --key python --value-file ./coverage.xml
      - persist_to_workspace:
          root: docs
          paths: 
            - coverage/*

  commit_coverage:
    description: push coverage back to git
    steps:
      - attach_workspace:
          at: docs
      - run:
          name: coverage
          command: |
            mkdir /tmp/docs/
            mkdir /tmp/docs/coverage/
            cp -ap ./docs/build/html/. /tmp/docs/
            cp -ap ./docs/coverage/. /tmp/docs/coverage/
            rm /tmp/docs/coverage/.gitignore
            git checkout gh-pages
            git pull
            rm -rf ./coverage/*
            cp -ap /tmp/docs/. ./
            find -type f -name '*!home!circleci!.pyenv!versions!*' -delete
            rm -f Makefile make.bat
            git config user.email "chinchalinchin@gmail.com"
            git config user.name "CircleCi Bot"
            git add .
            git commit -m "Pipeline Unit Tests & Documentation $(echo $(date))" || true
            git push --set-upstream origin gh-pages || true
        # No idea what the file *!home!circleci!.pyenv!versions!* is, but it's huge
        # and screws up the job. manually delete it until i figure out what is going on.
        # I think it probably has something to do with the cache?

jobs:
  pypi_micro_update:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - install_python_deps
      - run:
          name: iterate micro version
          command: |
            python ./scripts/circleci/iterate_version.py micro
      - build_wheel
      - upload_artifacts
      - commit_version

  pypi_minor_update:
    docker: 
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - install_python_deps
      - run:
          name: iterate minor version
          command: | 
            python ./scripts/circleci/iterate_version.py minor
      - build_wheel
      - upload_artifacts
      - commit_version

  pypi_major_update:
    docker: 
      - image: cimg/python:3.9.6
    steps:
      - checkout 
      - install_python_deps
      - run:
          name: iterate major version
          command: |
            python ./scripts/circleci/iterate_version.py major
      - build_wheel
      - upload_artifacts
      - commit_version

  dependencies: 
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - install_python_deps
      - install_test_deps
      - install_doc_deps

  unit_tests:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - run_unit_tests

  documentation:
    docker: 
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - generate_package_docs
      - generate_source_docs
      - commit_coverage

workflows:
  version: 2
  build_and_push:
    jobs:
      - pypi_micro_update:
          filters:
            branches:
              only:
                - pypi/micro-update
      - pypi_minor_update:
          filters: 
            branches:
              only:
                - pypi/minor-update
      - pypi_major_update:
          filters:
            branches:
              only:
                - pypi/major-update

  github_pages:
    jobs:
      - dependencies:
          filters: 
            branches:
              only:
                - develop/main
      - unit_tests:
          filters:
            branches:
              only:
                - develop/main
          requires: 
            - dependencies
      - documentation:
          filters:
            branches:
              only:
                - develop/main
          requires:
            - unit_tests
            - dependencies