version: 2.1

commands:
  install:
    description: install build dependencies
    steps:
      - run:
          name: dependency installation
          command: pip install twine setuptools build
  build:
    description: compress and build python package
    steps:
      - run:
          name: artifact build
          command: python -m build
  upload:
    description: upload package artifacts to PyPi
    steps:
      - run:
          name: artifact upload
          command: twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*
  
jobs:
  pypi:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - install
      - run:
          name: iterate subminor version
          command: |
            VERSION
      - build
      - upload

workflows:
  version: 2
  build_and_push:
    jobs:
      - pypi:
          filters:
            branches:
              only:
                - pypi/package-subminor